// <auto-generated />
using ImpostoRenda.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ImpostoRenda.Infrastructure.Migrations
{
    [DbContext(typeof(ImpostoRendaContex))]
    [Migration("20180818201734_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ImpostoRenda.Dominio.Entidades.SalarioMinino", b =>
                {
                    b.Property<int>("IdSalarioMinino")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Valor")
                        .HasColumnName("Valor");

                    b.HasKey("IdSalarioMinino");

                    b.ToTable("SalarioMinino");
                });
#pragma warning restore 612, 618
        }
    }
}
